### ISSUE TITLE
Improve final `Counter` module pen

### ISSUE THREAD

**Issue by jacobmllr95** [quilljs/quilljs.github.io#10]
This is not really an issue rather than some minor improvements to the "Wrapping It All Up" pen.
https://codepen.io/jackmu95/pen/amzAJZ

**Improvements:**
- Only use `let` and `const`
- Use template strings
- Set default value (word) for the `unit` option
- Rename `calculate` function to `getCount`
- Fix count calculation when `unit` is not set to `word`

**Comment by jhchen** [comment]
All the other pens are written in ES5. It doesn't make much sense to me to suddenly use ES6 in the final pen and I'm not sure it makes sense to convert all of them to ES6. `calculate` to `getCount` falls under this category as well. The last point I think is the result of other changes being made not in the original pen.
