### ISSUE TITLE
CodePens on http://quilljs.com/guides/cloning-medium-with-parchment/ don't work

### ISSUE THREAD

**Issue by eamodio** [quilljs/quilljs.github.io#11]
Since the 1.0 update, the CodePens on http://quilljs.com/guides/cloning-medium-with-parchment/ have lots of JS errors about `Uncaught TypeError: Quill.import is not a function`

**Comment by jhchen** [comment]
Thanks for the report! Looks like there was an issue with building quill.core.js that has been fixed. The correct build has been updated on the CDN and the errors should be gone on CodePen now. Builds in Github releases have also been updated.
