### ISSUE TITLE
Final CodePen on http://quilljs.com/guides/cloning-medium-with-parchment/ is missing the embeds

### ISSUE THREAD

**Issue by eamodio** [quilljs/quilljs.github.io#12]
In the "Final Polish" section the last CodePen is missing all the embeds (image, twitter, video) from the toolbar.

**Comment by jhchen** [comment]
It does what Medium does which is put it in its own container and only show on an empty line. I'm open to suggestions on making this more clear but it does a bunch of stuff like hide some buttons in the tooltip and make the editor span the page and I don't really want to talk about the UI as that's not the focus of the guide.

**Comment by eamodio** [comment]
Doh -- sorry about that -- I honestly never even tried adding a new line. :(

Maybe if it started blank - so the + would appear off the start?
