### ISSUE TITLE
Sourcecode not working correct

### ISSUE THREAD

**Issue by osworx** [quilljs/quilljs.github.io#20]
http://quilljs.com/playground/ > switching to source code seems to be working not correct.
For example, write a few lines and switch between source code and html view.
When in source code view all the text lines should be in that view, but currently only 1 or 2 or a few.
Switching back to html does not display all lines correct in html view - and vice versa.

**Comment by benbro** [comment]
What do you mean by 'source code view' and 'html view'?
Quill doesn't have 'view source' option.

If you are referring to the HTML tab on the left, it's part of [codepen](https://codepen.io), not part of the editor.

**Comment by osworx** [comment]
Seems that I have misinterpreted that icon - as it is normally a switch between source code and html view:
![quill_codeblock](https://cloud.githubusercontent.com/assets/1905204/18389976/a3475e28-76a8-11e6-9819-7cdc4840e82e.png)

If so, then sorry.
But if the editor has no source code view, he is not really useable (for some) - or is there somewhere a setting I have not found?

**Comment by benbro** [comment]
This button is for syntax highlighting code like javascript or python.

Previous discussion about raw html mode:
https://github.com/quilljs/quill/issues/128
