### ISSUE TITLE
Include a link to the 1.0 website on master

### ISSUE THREAD

**Issue by nacgarg** [quilljs/quilljs.github.io#3]
Adding a link to beta.quilljs.com in the sidebar at the bottom would be nice.

![image](https://cloud.githubusercontent.com/assets/8907939/16323607/db7a2030-3960-11e6-97b4-a3ddf34ffe94.png)

**Comment by jhchen** [comment]
Thank you for the suggestion. I'm planning on adding a notice at the top once the first release candidate is out and merge the two sites.
