### ISSUE TITLE
The codepen example can't get the source.

### ISSUE THREAD

**Issue by ghost** [quilljs/quilljs.github.io#8]
In documentation playground, the codepen examples like _http://codepen.io/quill/pen/dMQGmq_ that used the url _http://beta.quilljs.com/1.0.0-beta.9/quill.js_ ,but the resource was not found.Replace it by **http://cdn.quilljs.com/1.0.0-beta/**.11/,It resolved.

**Comment by jhchen** [comment]
Fixed thanks!
